### ISSUE TITLE
Google drive links

### ISSUE THREAD

**Issue by kanji1011** [spyflying/CMPC-Refseg#3]
Can you please share google drive links for checkpoint and glove embeddings? I am not able to access baidu link in my country.

**Comment by aditya10** [comment]
Hello!

I recently downloaded the files from Baidu. Here is the Drive link for the checkpoints: https://drive.google.com/drive/folders/1yRvwVAyYx1m1ICxEg-epLOYyn5qT9VIR?usp=sharing

And for the Glove Embeddings:
https://drive.google.com/drive/folders/1enhXZV7N1myoZTcvlfNvqw3_GVOelHs5?usp=sharing

Note: these links may not be active after a few days

**Comment by kanji1011** [comment]
Thanks a lot.
